### ISSUE TITLE
Script exits with code 1

### ISSUE THREAD

**Issue by denkristoffer** [iynere/compare-url-orb#11]
Hi 👋

I've been trying to use this orb but currently it exits with code 1. It seems to happen inside the loop but I'm not sure exactly where. I get the following output

```
checking if circle-2.1 is a new branch...
----------------------------------------------------------------------------------------------------
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100    37  100    37    0     0   1311      0 --:--:-- --:--:-- --:--:--  1321
----------------------------------------------------------------------------------------------------
yes, circle-2.1 is new and 4a8d5049b6faaed9a1afd96746023f3995e1d6a4 is its only commit
finding most recent ancestor commit from any other branch...
----------------------------------------------------------------------------------------------------
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100    37  100    37    0     0    918      0 --:--:-- --:--:-- --:--:--   925
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100    37  100    37    0     0   1320      0 --:--:-- --:--:-- --:--:--  1370
Exited with code 1
```

Do you have any idea what could cause this, or is there perhaps a way for me to debug this?

**Comment by jaumann** [comment]
I am having the exact same issue. If I re-run the step with ssh and run the command manually, it appears to work, leaving me to speculate that its an issue with the parameter replacement, as replacing the "<<parameters.XXXX>>" is the only thing I did to change the script

**Comment by jaumann** [comment]
The issue appears to be that the type `env_var_name` isn't getting translated to an ENV when the template is run. This results in the entry `<<parameters.circle-token>>` being replaced with `CIRCLE_TOKEN` instead of `$CIRCLE_TOKEN`. I was able to get mine working by adding a `$` before the parameter in the command, but that seems like it is something that should be getting taken care of by the fact that the `circle-token` parameter is a type `env_var_name`. Any thoughts?

**Comment by iynere** [comment]
thanks for catching this y'all ! it's a simple typo, so i pushed the fix str8 to master. check for version `0.3.2` in a second: https://circleci.com/orbs/registry/orb/iynere/compare-url

**Comment by iynere** [comment]
oh, just kidding, it bumped to `0.4.0`. thanks again ! @jaumann @denkristoffer

**Comment by denkristoffer** [comment]
I'm actually still seeing the same behaviour with 0.4.4. Are things working for you now @jaumann?

**Comment by jaumann** [comment]
@denkristoffer I changed my pointer to orb to `0.4.0` and it appears to work now for me. I would guess your use case is probably the same as mine, which is to use this in a `.circleci/config.yml` file for building and deploying orbs?

If so, the way I tracked down my initial problem was to actually get the output of the orb used in the context of my orb using the circleci cli tools `circleci orb process config.yml` and re-ran my job with ssh. Then I stepped through the lines of the command until I found where it broke. 

Not very efficient, but it was the best way I could think to debug these orbs as they currently are used now.

**Comment by iynere** [comment]
@denkristoffer there's a number of edge cases where this orb doesn't function as expected (see the issues)—in all those cases, i would imagine it would exit with code 1. can you say a little more about what exactly was happening when you saw this issue ?

**Comment by iynere** [comment]
@denkristoffer also, i recommend setting the `debug` parameter to `true` https://github.com/iynere/compare-url-orb#parameters

**Comment by iynere** [comment]
no worries ! happy to hear you figured things out 🙂

**Comment by iynere** [comment]
locking the convo here, as there could be any number of reasons why the orb might exit with code 1. if any other folks see an exit code 1, please open a new issue & describe what happened in detail 🙏
